BariiLi/Controllers/AppointmentSystemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BariiLi.Data;
using BariiLi.Models;

namespace BariiLi.Controllers
{
    public class AppointmentSystemsController : Controller
    {
        private readonly BariiLiContext _context;

        public AppointmentSystemsController(BariiLiContext context)
        {
            _context = context;
        }

        // GET: AppointmentSystems
        public async Task<IActionResult> Index()
        {
            return View(await _context.AppointmentSystems.ToListAsync());
        }

        // GET: AppointmentSystems/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointmentSystems = await _context.AppointmentSystems
                .FirstOrDefaultAsync(m => m.typeOfPain == id);
            if (appointmentSystems == null)
            {
                return NotFound();
            }

            return View(appointmentSystems);
        }

        // GET: AppointmentSystems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AppointmentSystems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("typeOfPain,MTId,patientId,availabilityQueues")] AppointmentSystems appointmentSystems)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appointmentSystems);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(appointmentSystems);
        }

        // GET: AppointmentSystems/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointmentSystems = await _context.AppointmentSystems.FindAsync(id);
            if (appointmentSystems == null)
            {
                return NotFound();
            }
            return View(appointmentSystems);
        }

        // POST: AppointmentSystems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("typeOfPain,MTId,patientId,availabilityQueues")] AppointmentSystems appointmentSystems)
        {
            if (id != appointmentSystems.typeOfPain)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointmentSystems);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentSystemsExists(appointmentSystems.typeOfPain))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appointmentSystems);
        }

        // GET: AppointmentSystems/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointmentSystems = await _context.AppointmentSystems
                .FirstOrDefaultAsync(m => m.typeOfPain == id);
            if (appointmentSystems == null)
            {
                return NotFound();
            }

            return View(appointmentSystems);
        }

        // POST: AppointmentSystems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var appointmentSystems = await _context.AppointmentSystems.FindAsync(id);
            _context.AppointmentSystems.Remove(appointmentSystems);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentSystemsExists(string id)
        {
            return _context.AppointmentSystems.Any(e => e.typeOfPain == id);
        }
    }
}

BariiLi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BariiLi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

                <div class="container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">צור קשר</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AppointmentSystems" asp-action="Create">Create an appointement</a>                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUsPlastical">ניתוחים פלסטיים</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">רפואה כללית</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="HomePage">דף הבית</a>
                            </li>
                            <li class="nav-item" id="sign-in">
                                <a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="HomePage"> התחבר</a>
                            </li>

                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        </ul>
                    </div>
                </div>
            </nav>*@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="" navbar-collapse collapse order-2 order-sm-1"> @*Signin button connected to modal by id="signInModal:*@ 
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item"><a class="btn btn-outline-secondary" data-toggle="modal" data-target="#signInModal">התחבר</a></li>
                </ul>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".collapse">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a href="#" class="navbar-brand order-sm-2 order-1">Logo</a>
            <div class="navbar-collapse collapse order-2 order-sm-1 justify-content-end">
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">צור קשר</a>
                    </li>
                    @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AppointmentSystems" asp-action="Create">Create an appointement</a>
                        </li>*@
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUsPlastical">ניתוחים פלסטיים</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">רפואה כללית</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="HomePage">דף הבית</a>
                    </li>
                </ul>
            </div>

        </nav>
    </header>

    <!-- Modal -->
    <div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100 font-weight-bold">Sign in</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body mx-3 ">
                    <div class="md-form mb-5">
                        <i class="fas fa-envelope prefix grey-text"></i>
                        <input type="number" id="defaultForm" class="form-control validate">
                        <label data-error="wrong" data-success="right" class="text-center" for="defaultForm-email">ת.ז</label>
                    </div>

                    <div class="md-form mb-4">
                        <i class="fas fa-lock prefix grey-text"></i>
                        <input type="password" id="defaultForm-pass" class="form-control validate">
                        <label data-error="wrong" data-success="right" for="defaultForm-pass">סיסמא</label>
                    </div>

                </div>
                <div class="modal-footer d-flex justify-content-center">
                    <button class="btn btn-default">התחבר</button>
                </div>
            </div>
        </div>
    </div>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - BariiLi - <a asp-area="" asp-controller="Home" asp-action="ContactUs">Contact us</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
</body>
</html>